
<hr>

```{r plotDiffPathway, eval=displayDiffPathway, echo=FALSE, warning=FALSE, message=FALSE, results='asis', fig.align="center", fig.cap=figRef("plotDiffPathway", "Heatmap of enriched pathways in differentially expressed genes", trunk.eval=displayDiffPathway), fig.height=getHeatmapHeight(plotData$diffFC$pathways), fig.width=10}
heatmap.2(as.matrix(plotData$diffFC$pathways), cexRow = 0.6, margins=heatmapMargins, keysize=heatmapKeysize, col=heatmapPathwayColors)
```

scRNABatchQC performs the functional enrichment analysis for differentially expressed genes in each pairwise comparison. 

```{r showDiffPathway, eval=hasDiffPathway, echo=FALSE, warning=FALSE, message=FALSE, results='asis'}
cat(paste0(figRef("plotDiffPathway"), " shows the log-pvalue for enriched pathways in each pairwise comparison. <hr>"))
```

```{r tableDiffPathway, eval=hasDiffPathway, echo=FALSE, results="asis"}
pw<-plotData$diffFC$pathways
pw[pw<0]<-0
pw10<-10 ^ (-pw)
pw10[pw10>0.9]<-1
pw10<-format(pw10, digits = 3)
pw10[pw10 == "1.00e+00"] <- ""
kable(pw10, caption=tabRef("tableDiffPathway", "Enriched pathways in differentially expressed genes"))
```

```{r showDiffPathwayTable, eval=hasDiffPathway, echo=FALSE, warning=FALSE, message=FALSE, results='asis'}
cat(paste0(tabRef("tableDiffPathway"), " shows the enriched pathways based on differentially expressed genes between experiments."))
```

```{r showNoDiffPathway, eval=!hasDiffPathway, echo=FALSE, warning=FALSE, message=FALSE, results='asis'}
cat("But no enriched pathway detected.")
```


